version: '3.7'

services:

  frontend:
    container_name: nackad-frontend
    command: ["npm","run","start"]
    build:
      context: ./server/frontend
    ports:
      - '3000:3000'
    volumes:
      - ./server/frontend/src:/app/frontend/src
    env_file:
      - env_development.env

  backend:
    container_name: nackad-backend
    command: ["npm","run","dev"]
    build:
      context: ./server/backend
    ports:
      - '3001:3000'
    volumes:
      - ./server/backend/src:/app/backend/src
    env_file:
      - env_development.env

  mongodb:
    container_name: nackad-database
    build:
      context: ./mongodb
    volumes:
      - ./data/db:/data/db
    ports:
      - '27018:27017'
    env_file:
      - env_development.env
