FROM node:17-alpine

# Prepare frontend
WORKDIR /app/frontend/
COPY ./frontend/package.json ./
RUN npm install

COPY ./frontend .
RUN npm run build
RUN mv ./frontend/build /app/backend/public

WORKDIR /app/backend
COPY package.json ./
RUN npm install

WORKDIR /app/backend/
COPY ./backend .
RUN npm run build

EXPOSE 3000
CMD ["npm","dev"]