const localPick = {
  id: 4732170010871,
  admin_graphql_api_id: 'gid: //shopify/Order/4732170010871',
  app_id: 580111,
  browser_ip: '84.112.77.200',
  buyer_accepts_marketing: false,
  cancel_reason: null,
  cancelled_at: null,
  cart_token: null,
  checkout_id: 32572257927415,
  checkout_token: 'cb3aa411e93a83978c990c251c5c362e',
  client_details: {
    accept_language: 'en-US,en;q=0.9,de-AT;q=0.8,de;q=0.7,tr-TR;q=0.6,tr;q=0.5',
    browser_height: 880,
    browser_ip: '84.112.77.200',
    browser_width: 1920,
    session_hash: null,
    user_agent:
      'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36'
  },
  closed_at: null,
  confirmed: true,
  contact_email: 'mustafa.cicek@live.at',
  created_at: '2022-04-14T00:22:32+02:00',
  currency: 'EUR',
  current_subtotal_price: '22.91',
  current_subtotal_price_set: {
    shop_money: { amount: '22.91', currency_code: 'EUR' },
    presentment_money: { amount: '22.91', currency_code: 'EUR' }
  },
  current_total_discounts: '9.81',
  current_total_discounts_set: {
    shop_money: { amount: '9.81', currency_code: 'EUR' },
    presentment_money: { amount: '9.81', currency_code: 'EUR' }
  },
  current_total_duties_set: null,
  current_total_price: '22.91',
  current_total_price_set: {
    shop_money: { amount: '22.91', currency_code: 'EUR' },
    presentment_money: { amount: '22.91', currency_code: 'EUR' }
  },
  current_total_tax: '2.83',
  current_total_tax_set: {
    shop_money: { amount: '2.83', currency_code: 'EUR' },
    presentment_money: { amount: '2.83', currency_code: 'EUR' }
  },
  customer_locale: 'de-AT',
  device_id: null,
  discount_codes: [{ code: 'CEOLIFE', amount: '9.81', type: 'percentage' }],
  email: 'mustafa.cicek@live.at',
  estimated_taxes: false,
  financial_status: 'paid',
  fulfillment_status: null,
  gateway: 'credit_card_mollie_',
  landing_site: '/',
  landing_site_ref: null,
  location_id: null,
  name: 'ND1068',
  note: '',
  note_attributes: [
    { name: 'deliveryDay', value: '2022-04-14' },
    { name: 'timeslot', value: '15:00-16:00' }
  ],
  number: 68,
  order_number: 1068,
  order_status_url:
    'https: //nackad.at/61031416055/orders/cec0bc26f9c45455745e6221df626536/authenticate?key=3500472fcd2257360b29792819aa02ef',
  original_total_duties_set: null,
  payment_gateway_names: ['credit_card_mollie_'],
  phone: null,
  presentment_currency: 'EUR',
  processed_at: '2022-04-07T00: 22: 31+02: 00',
  processing_method: 'offsite',
  reference: null,
  referring_site: '',
  source_identifier: null,
  source_name: 'web',
  source_url: null,
  subtotal_price: '22.91',
  subtotal_price_set: {
    shop_money: { amount: '22.91', currency_code: 'EUR' },
    presentment_money: { amount: '22.91', currency_code: 'EUR' }
  },
  tags: '',
  tax_lines: [
    {
      price: '1.65',
      rate: 0.2,
      title: 'AT VAT',
      price_set: [Object],
      channel_liable: false
    },
    {
      price: '1.18',
      rate: 0.1,
      title: 'AT VAT',
      price_set: [Object],
      channel_liable: false
    }
  ],
  taxes_included: true,
  test: false,
  token: 'cec0bc26f9c45455745e6221df626536',
  total_discounts: '9.81',
  total_discounts_set: {
    shop_money: { amount: '9.81', currency_code: 'EUR' },
    presentment_money: { amount: '9.81', currency_code: 'EUR' }
  },
  total_line_items_price: '32.72',
  total_line_items_price_set: {
    shop_money: { amount: '32.72', currency_code: 'EUR' },
    presentment_money: { amount: '32.72', currency_code: 'EUR' }
  },
  total_outstanding: '0.00',
  total_price: '22.91',
  total_price_set: {
    shop_money: { amount: '22.91', currency_code: 'EUR' },
    presentment_money: { amount: '22.91', currency_code: 'EUR' }
  },
  total_price_usd: '24.99',
  total_shipping_price_set: {
    shop_money: { amount: '0.00', currency_code: 'EUR' },
    presentment_money: { amount: '0.00', currency_code: 'EUR' }
  },
  total_tax: '2.83',
  total_tax_set: {
    shop_money: { amount: '2.83', currency_code: 'EUR' },
    presentment_money: { amount: '2.83', currency_code: 'EUR' }
  },
  total_tip_received: '0.00',
  total_weight: 0,
  updated_at: '2022-04-07T00: 22: 34+02: 00',
  user_id: null,
  billing_address: {
    first_name: 'Mustafa',
    address1: 'Leibnizgasse 61',
    phone: '+436603556067',
    city: 'Wien',
    zip: '1100',
    province: null,
    country: 'Austria',
    last_name: 'Cicek',
    address2: '',
    company: '',
    latitude: 48.1698123,
    longitude: 16.374732,
    name: 'Mustafa Cicek',
    country_code: 'AT',
    province_code: null
  },
  customer: {
    id: 5951129387255,
    email: 'mustafa.cicek@live.at',
    accepts_marketing: true,
    created_at: '2021-11-22T17: 23: 46+01: 00',
    updated_at: '2022-04-07T00: 22: 33+02: 00',
    first_name: 'Mustafa',
    last_name: 'Cicek',
    orders_count: 3,
    state: 'enabled',
    total_spent: '78.42',
    last_order_id: 4732170010871,
    note: null,
    verified_email: true,
    multipass_identifier: null,
    tax_exempt: false,
    phone: null,
    tags: 'password page, prospect',
    last_order_name: 'ND1068',
    currency: 'EUR',
    accepts_marketing_updated_at: '2021-11-22T17: 23: 46+01: 00',
    marketing_opt_in_level: 'single_opt_in',
    sms_marketing_consent: null,
    admin_graphql_api_id: 'gid: //shopify/Customer/5951129387255',
    default_address: {
      id: 7631599829239,
      customer_id: 5951129387255,
      first_name: 'Mustafa',
      last_name: 'Cicek',
      company: '',
      address1: 'Leibnizgasse 61',
      address2: '',
      city: 'Wien',
      province: null,
      country: 'Austria',
      zip: '1100',
      phone: '+436603556067',
      name: 'Mustafa Cicek',
      province_code: null,
      country_code: 'AT',
      country_name: 'Austria',
      default: true
    }
  },
  discount_applications: [
    {
      target_type: 'line_item',
      type: 'discount_code',
      value: '30.0',
      value_type: 'percentage',
      allocation_method: 'across',
      target_selection: 'all',
      code: 'CEOLIFE'
    }
  ],
  fulfillments: [],
  line_items: [
    {
      id: 12117958033655,
      admin_graphql_api_id: 'gid: //shopify/LineItem/12117958033655',
      destination_location: [Object],
      fulfillable_quantity: 2,
      fulfillment_service: 'manual',
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: 'Brauerei Hirt Bio Kellermeister MW 0,5 l',
      origin_location: [Object],
      price: '1.34',
      price_set: [Object],
      product_exists: true,
      product_id: 7550388175095,
      properties: [],
      quantity: 2,
      requires_shipping: true,
      sku: '',
      taxable: true,
      title: 'Brauerei Hirt Bio Kellermeister MW 0,5 l',
      total_discount: '0.00',
      total_discount_set: [Object],
      variant_id: 42471073382647,
      variant_inventory_management: 'shopify',
      variant_title: '',
      vendor: 'nackad.at',
      tax_lines: [Array],
      duties: [],
      discount_allocations: [Array]
    },
    {
      id: 12117958066423,
      admin_graphql_api_id: 'gid: //shopify/LineItem/12117958066423',
      destination_location: [Object],
      fulfillable_quantity: 1,
      fulfillment_service: 'manual',
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: 'Bio Linsen rot 500g',
      origin_location: [Object],
      price: '2.09',
      price_set: [Object],
      product_exists: true,
      product_id: 7559707820279,
      properties: [],
      quantity: 1,
      requires_shipping: true,
      sku: '',
      taxable: true,
      title: 'Bio Linsen rot 500g',
      total_discount: '0.00',
      total_discount_set: [Object],
      variant_id: 42501574263031,
      variant_inventory_management: 'shopify',
      variant_title: '',
      vendor: 'nackad.at',
      tax_lines: [Array],
      duties: [],
      discount_allocations: [Array]
    },
    {
      id: 12117958099191,
      admin_graphql_api_id: 'gid: //shopify/LineItem/12117958099191',
      destination_location: [Object],
      fulfillable_quantity: 1,
      fulfillment_service: 'manual',
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: 'Bio Langkornreis weiß 700g',
      origin_location: [Object],
      price: '2.49',
      price_set: [Object],
      product_exists: true,
      product_id: 7554052096247,
      properties: [],
      quantity: 1,
      requires_shipping: true,
      sku: '',
      taxable: true,
      title: 'Bio Langkornreis weiß 700g',
      total_discount: '0.00',
      total_discount_set: [Object],
      variant_id: 42483806601463,
      variant_inventory_management: 'shopify',
      variant_title: '',
      vendor: 'nackad.at',
      tax_lines: [Array],
      duties: [],
      discount_allocations: [Array]
    },
    {
      id: 12117958131959,
      admin_graphql_api_id: 'gid: //shopify/LineItem/12117958131959',
      destination_location: [Object],
      fulfillable_quantity: 1,
      fulfillment_service: 'manual',
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: 'Die Hoflieferanten Bio Natur Joghurt 500 g',
      origin_location: [Object],
      price: '1.69',
      price_set: [Object],
      product_exists: true,
      product_id: 7463566999799,
      properties: [],
      quantity: 1,
      requires_shipping: true,
      sku: '',
      taxable: true,
      title: 'Die Hoflieferanten Bio Natur Joghurt 500 g',
      total_discount: '0.00',
      total_discount_set: [Object],
      variant_id: 42120483471607,
      variant_inventory_management: 'shopify',
      variant_title: '',
      vendor: 'nomnom-market',
      tax_lines: [Array],
      duties: [],
      discount_allocations: [Array]
    },
    {
      id: 12117958164727,
      admin_graphql_api_id: 'gid: //shopify/LineItem/12117958164727',
      destination_location: [Object],
      fulfillable_quantity: 1,
      fulfillment_service: 'manual',
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: 'Bio Bananen ca 500 g',
      origin_location: [Object],
      price: '1.99',
      price_set: [Object],
      product_exists: true,
      product_id: 7464455307511,
      properties: [],
      quantity: 1,
      requires_shipping: true,
      sku: '',
      taxable: true,
      title: 'Bio Bananen ca 500 g',
      total_discount: '0.00',
      total_discount_set: [Object],
      variant_id: 42124058132727,
      variant_inventory_management: 'shopify',
      variant_title: '',
      vendor: 'nomnom-market',
      tax_lines: [Array],
      duties: [],
      discount_allocations: [Array]
    },
    {
      id: 12117958197495,
      admin_graphql_api_id: 'gid: //shopify/LineItem/12117958197495',
      destination_location: [Object],
      fulfillable_quantity: 1,
      fulfillment_service: 'manual',
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: 'Rapunzel Bio Getrocknete Mangos 100g',
      origin_location: [Object],
      price: '1.97',
      price_set: [Object],
      product_exists: true,
      product_id: 7553231028471,
      properties: [],
      quantity: 1,
      requires_shipping: true,
      sku: '',
      taxable: true,
      title: 'Rapunzel Bio Getrocknete Mangos 100g',
      total_discount: '0.00',
      total_discount_set: [Object],
      variant_id: 42480283615479,
      variant_inventory_management: 'shopify',
      variant_title: '',
      vendor: 'nackad.at',
      tax_lines: [Array],
      duties: [],
      discount_allocations: [Array]
    },
    {
      id: 12117958230263,
      admin_graphql_api_id: 'gid: //shopify/LineItem/12117958230263',
      destination_location: [Object],
      fulfillable_quantity: 1,
      fulfillment_service: 'manual',
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: 'Bio Eichblatt grün 1 Stk.',
      origin_location: [Object],
      price: '2.39',
      price_set: [Object],
      product_exists: true,
      product_id: 7570583322871,
      properties: [],
      quantity: 1,
      requires_shipping: true,
      sku: '',
      taxable: true,
      title: 'Bio Eichblatt grün 1 Stk.',
      total_discount: '0.00',
      total_discount_set: [Object],
      variant_id: 42559863423223,
      variant_inventory_management: 'shopify',
      variant_title: '',
      vendor: 'nomnom-market',
      tax_lines: [Array],
      duties: [],
      discount_allocations: [Array]
    },
    {
      id: 12117958263031,
      admin_graphql_api_id: 'gid: //shopify/LineItem/12117958263031',
      destination_location: [Object],
      fulfillable_quantity: 1,
      fulfillment_service: 'manual',
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: 'Bio Tomaten Cherry Rispe Aroma 250g',
      origin_location: [Object],
      price: '2.99',
      price_set: [Object],
      product_exists: true,
      product_id: 7564440994039,
      properties: [],
      quantity: 1,
      requires_shipping: true,
      sku: '',
      taxable: true,
      title: 'Bio Tomaten Cherry Rispe Aroma 250g',
      total_discount: '0.00',
      total_discount_set: [Object],
      variant_id: 42532988518647,
      variant_inventory_management: 'shopify',
      variant_title: '',
      vendor: 'nomnom-market',
      tax_lines: [Array],
      duties: [],
      discount_allocations: [Array]
    },
    {
      id: 12117958295799,
      admin_graphql_api_id: 'gid: //shopify/LineItem/12117958295799',
      destination_location: [Object],
      fulfillable_quantity: 1,
      fulfillment_service: 'manual',
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: 'Bio Karfiol/Blumenkohl 1 Stk',
      origin_location: [Object],
      price: '2.99',
      price_set: [Object],
      product_exists: true,
      product_id: 7570588598519,
      properties: [],
      quantity: 1,
      requires_shipping: true,
      sku: '',
      taxable: true,
      title: 'Bio Karfiol/Blumenkohl 1 Stk',
      total_discount: '0.00',
      total_discount_set: [Object],
      variant_id: 42559879938295,
      variant_inventory_management: 'shopify',
      variant_title: '',
      vendor: 'nomnom-market',
      tax_lines: [Array],
      duties: [],
      discount_allocations: [Array]
    },
    {
      id: 12117958328567,
      admin_graphql_api_id: 'gid: //shopify/LineItem/12117958328567',
      destination_location: [Object],
      fulfillable_quantity: 1,
      fulfillment_service: 'manual',
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: 'Almdudler Original 1 l',
      origin_location: [Object],
      price: '1.69',
      price_set: [Object],
      product_exists: true,
      product_id: 7470551335159,
      properties: [],
      quantity: 1,
      requires_shipping: true,
      sku: '',
      taxable: true,
      title: 'Almdudler Original 1 l',
      total_discount: '0.00',
      total_discount_set: [Object],
      variant_id: 42143660736759,
      variant_inventory_management: 'shopify',
      variant_title: '',
      vendor: 'nomnom-market',
      tax_lines: [Array],
      duties: [],
      discount_allocations: [Array]
    },
    {
      id: 12117958361335,
      admin_graphql_api_id: 'gid: //shopify/LineItem/12117958361335',
      destination_location: [Object],
      fulfillable_quantity: 4,
      fulfillment_service: 'manual',
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: 'Makava Bio Delighted ice tea 0,33 l',
      origin_location: [Object],
      price: '1.44',
      price_set: [Object],
      product_exists: true,
      product_id: 7465249112311,
      properties: [],
      quantity: 4,
      requires_shipping: true,
      sku: '',
      taxable: true,
      title: 'Makava Bio Delighted ice tea 0,33 l',
      total_discount: '0.00',
      total_discount_set: [Object],
      variant_id: 42128054354167,
      variant_inventory_management: 'shopify',
      variant_title: '',
      vendor: 'nomnom-market',
      tax_lines: [Array],
      duties: [],
      discount_allocations: [Array]
    },
    {
      id: 12117958394103,
      admin_graphql_api_id: 'gid: //shopify/LineItem/12117958394103',
      destination_location: [Object],
      fulfillable_quantity: 1,
      fulfillment_service: 'manual',
      fulfillment_status: null,
      gift_card: false,
      grams: 0,
      name: 'Graf Bio Welschriesling MW 1 l',
      origin_location: [Object],
      price: '3.99',
      price_set: [Object],
      product_exists: true,
      product_id: 7550392860919,
      properties: [],
      quantity: 1,
      requires_shipping: true,
      sku: '',
      taxable: true,
      title: 'Graf Bio Welschriesling MW 1 l',
      total_discount: '0.00',
      total_discount_set: [Object],
      variant_id: 42471101071607,
      variant_inventory_management: 'shopify',
      variant_title: '',
      vendor: 'nackad.at',
      tax_lines: [Array],
      duties: [],
      discount_allocations: [Array]
    }
  ],
  payment_terms: null,
  refunds: [],
  shipping_lines: [
    {
      id: 3936700760311,
      carrier_identifier: '650f1a14fa979ec5c74d063e968411d4',
      code: 'Lager Wien 1120',
      delivery_category: null,
      discounted_price: '0.00',
      discounted_price_set: [Object],
      phone: null,
      price: '0.00',
      price_set: [Object],
      requested_fulfillment_service_id: null,
      source: 'shopify',
      title: 'Lager Wien 1120',
      tax_lines: [Array],
      discount_allocations: []
    }
  ]
}

export default localPick
