name: Github Actions Pipeline

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          
      - name: Install dependencies
        run: npm install
        working-directory: server/backend
        
      # Runs a single command using the runners shell
      - name: Run tests
        run: npm run test
        working-directory: server/backend
          
